name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          pip install huggingface_hub

      - name: Clone HF Space repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
        run: |
          echo "Clonage de l’espace Hugging Face : $SPACE_ID"
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/$SPACE_ID hf-space

      - name: Copy files safely
        run: |
          shopt -s extglob
          echo "Nettoyage de l'espace local..."
          cd hf-space
          git ls-files | xargs rm -f
          cd ..
          
          echo "Copie des fichiers sans le dossier hf-space"
          # Copie sans inclure le dossier hf-space lui-même
          cp -r !(hf-space) hf-space/

      - name: Commit & Push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf-space
          git add .
          git commit -m "Mise à jour via GitHub Actions"
          git push origin main
