name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          pip install huggingface_hub

      - name: Clone HF Space repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
        run: |
          echo "Clonage de l’espace Hugging Face : $SPACE_ID"
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/$SPACE_ID hf-space

      - name: Copy files
        run: |
          echo "Copie des fichiers locaux vers l’espace"
          cd hf-space
          git ls-files | xargs rm -f
          cd ..
          cp -r . hf-space/
          rm -rf hf-space/.git hf-space/.github

      - name: Commit & Push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf-space
          git add .
          git commit -m "Mise à jour via GitHub Actions"
          git push origin main
